name: Deploy React App to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd WeatherForecast  # ✅ Ensure you're in the correct directory
          npm install

      - name: Build React App
        run: |
          cd WeatherForecast
          npm run build

      - name: Disable Jekyll
        run: touch WeatherForecast/dist/.nojekyll  # ✅ Creates the file

      - name: Debug: List files in dist/
        run: ls -la WeatherForecast/dist  # ✅ Check if .nojekyll exists

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: WeatherForecast/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
